[package]
name = "foxie_base"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
libbinder = { version = "0.1.0", path = "../../libs/libbinder/libbinder" }
libbinder-basic = { version = "0.1.0", path = "../../libs/libbinder/extras/libbinder-basic", features = ["macros"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.21"
